version: '3.8'

services:
  myrcvdocker:
    image: myrcvdocker:latest
    # build:
    #   context: .
    network_mode: "host"  # 네트워크 설정을 호스트와 동일하게
    volumes:
      - /home/kwh/workspace:/root/workspace  # 지정한 경로로 볼륨 마운트
    command: tail -f /dev/null  # 컨테이너 시작 시 bash 실행
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]