version: '3.8'

services:
  myrcvdocker:
    image: myrcvdocker:0.0.0.1.dev
    build:
      context: .
    ports:
      - "8080:8080"  # 필요한 포트를 여기에 추가하세요
    environment:
      - ENV_VAR_NAME=value  # 필요한 환경 변수를 여기에 추가하세요
    volumes:
      - ./data:/app/data  # 필요한 볼륨을 여기에 추가하세요